// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq_v-hTbHybEsnYwoxfpbEPXvhkGb86QQ',
    appId: '1:436700117953:web:4a772eb309d8de47d2cd40',
    messagingSenderId: '436700117953',
    projectId: 'gastugas-f9039',
    authDomain: 'gastugas-f9039.firebaseapp.com',
    storageBucket: 'gastugas-f9039.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDMqPOu66qrVsCH9DivispJqSXnB8FMeU',
    appId: '1:436700117953:android:b07c22011a4272c3d2cd40',
    messagingSenderId: '436700117953',
    projectId: 'gastugas-f9039',
    storageBucket: 'gastugas-f9039.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqQAXBekXZY72PVfRDQSxPoxP4iR6EvwE',
    appId: '1:436700117953:ios:366d516306898aa0d2cd40',
    messagingSenderId: '436700117953',
    projectId: 'gastugas-f9039',
    storageBucket: 'gastugas-f9039.firebasestorage.app',
    androidClientId: '436700117953-vkmt7vlkgg80nksvt6l5sj3pe4i3v61h.apps.googleusercontent.com',
    iosClientId: '436700117953-rlmdn2jumv6mt09hj9jh63vtgd232r6m.apps.googleusercontent.com',
    iosBundleId: 'com.example.gastugasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqQAXBekXZY72PVfRDQSxPoxP4iR6EvwE',
    appId: '1:436700117953:ios:366d516306898aa0d2cd40',
    messagingSenderId: '436700117953',
    projectId: 'gastugas-f9039',
    storageBucket: 'gastugas-f9039.firebasestorage.app',
    androidClientId: '436700117953-vkmt7vlkgg80nksvt6l5sj3pe4i3v61h.apps.googleusercontent.com',
    iosClientId: '436700117953-rlmdn2jumv6mt09hj9jh63vtgd232r6m.apps.googleusercontent.com',
    iosBundleId: 'com.example.gastugasApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq_v-hTbHybEsnYwoxfpbEPXvhkGb86QQ',
    appId: '1:436700117953:web:93c66a77a28ebdfbd2cd40',
    messagingSenderId: '436700117953',
    projectId: 'gastugas-f9039',
    authDomain: 'gastugas-f9039.firebaseapp.com',
    storageBucket: 'gastugas-f9039.firebasestorage.app',
  );
}
